language: node_js

sudo: false

cache: npm

# test on node.js versions
node_js:
  - '14'
  - '12'
  - '10'

install:
  # ensure unexpected changes to yarn.lock break the build
  - npm install

script:
  - npm run test

after_script:
  - npm run coveralls
